[tool.black]
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
     /\..*
    |/.direnv/
)
'''

[tool.isort]
profile = "black"
known_first_party = "taxi_petzi"
default_section = "THIRDPARTY"
line_length = 88
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = 3
include_trailing_comma = true
